### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by dan-da** [davidrusu/bft-crdts#13]
I modified the test orswot::bft_orswot_net::tests::prop_adds_show_up_on_read to return failure, piped the output to a logfile.

I am seeing errors like:

```
[DSB/BFT_OP/INVALID] peer already exists MembershipNewPeer(i:effb..)...
[DSB/INVALID] failed bft op validation RequestValidation...
[DSB/INVALID] not the next msg RequestValidation...
[ORSWOT/VALIDATION] Dot is not a direct successor...
[DSB/BFT_OP/INVALID] failed algo validation...
```

Are these normal/ok, or is there an error in the logic somewhere?

log attached.
[bft.log](https://github.com/davidrusu/bft-crdts/files/5345636/bft.log)

**Comment by davidrusu** [comment]
> [DSB/BFT_OP/INVALID] peer already exists MembershipNewPeer(i:effb..)...

This is an artifact of from trying to keep the code simple. When an actor is the founding member of the network, it automatically adds itself to the network, but we still broadcast a request for membership, since this actor is a member of the network, it will send itself that request.

> [DSB/INVALID] failed bft op validation RequestValidation...

Just a generic log that is printed on every failed validation, this is from the same cause as the one above.

> [DSB/INVALID] not the next msg RequestValidation...
> [ORSWOT/VALIDATION] Dot is not a direct successor...
> [DSB/BFT_OP/INVALID] failed algo validation..
This one is more worrisome, more from a usability point of view.

Since our test case first initializes each proc on the network followed by sending out membership requests, this means that the first proc who joins the network can't send anymore requests after making the invalid membership request (as outlined above).

This is a problem with the test case logic, but perhaps we can make the system more flexible in that we make membership requests idempotent. This way we keep the test case logic simple (and in turn simpler UX), and modify our validation logic to allow duplicate membership requests from peers. I made the change in #14

**Comment by davidrusu** [comment]
Note, you will still see some of these logs with #14:

```
[DSB/INVALID] not the next msg RequestValidation...
[ORSWOT/VALIDATION] Dot is not a direct successor...
[DSB/BFT_OP/INVALID] failed algo validation..
```

This happens when packets are delivered out of order, or messages are generated with the same dot as other messages.
